# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lukas/beuth-cloud/02_DigiSys_CAE/Projektaufgabe/signal_generator_vivado/signal_generator_vivado.srcs/sources_1/ip/uart/uart.xci
# IP: The module: 'uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lukas/beuth-cloud/02_DigiSys_CAE/Projektaufgabe/signal_generator_vivado/signal_generator_vivado.srcs/sources_1/ip/uart/uart_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lukas/beuth-cloud/02_DigiSys_CAE/Projektaufgabe/signal_generator_vivado/signal_generator_vivado.srcs/sources_1/ip/uart/uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lukas/beuth-cloud/02_DigiSys_CAE/Projektaufgabe/signal_generator_vivado/signal_generator_vivado.srcs/sources_1/ip/uart/uart.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lukas/beuth-cloud/02_DigiSys_CAE/Projektaufgabe/signal_generator_vivado/signal_generator_vivado.srcs/sources_1/ip/uart/uart.xci
# IP: The module: 'uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lukas/beuth-cloud/02_DigiSys_CAE/Projektaufgabe/signal_generator_vivado/signal_generator_vivado.srcs/sources_1/ip/uart/uart_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lukas/beuth-cloud/02_DigiSys_CAE/Projektaufgabe/signal_generator_vivado/signal_generator_vivado.srcs/sources_1/ip/uart/uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lukas/beuth-cloud/02_DigiSys_CAE/Projektaufgabe/signal_generator_vivado/signal_generator_vivado.srcs/sources_1/ip/uart/uart.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
