# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/signal_generator.xdc

# IP: ip/adc_data_2/adc_data_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_data_2 || ORIG_REF_NAME==adc_data_2} -quiet] -quiet
