#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Oct 15 19:30:44 UTC 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 461615971a294f9c8ec05f3dd480d5c5 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot signal_generator_tb_func_synth xil_defaultlib.signal_generator_tb -log elaborate.log"
xelab -wto 461615971a294f9c8ec05f3dd480d5c5 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot signal_generator_tb_func_synth xil_defaultlib.signal_generator_tb -log elaborate.log

