#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Nov 13 19:10:34 CET 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 77ee92a1bc6f426a9695a74db8de5d6c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot signal_generator_tb_func_impl xil_defaultlib.signal_generator_tb -log elaborate.log"
xelab -wto 77ee92a1bc6f426a9695a74db8de5d6c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot signal_generator_tb_func_impl xil_defaultlib.signal_generator_tb -log elaborate.log

