# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lukas/01_Studium/02_DigiSys_CAE/Projektaufgabe/signal_generator_vivado/signal_generator_vivado.srcs/sources_1/ip/sin_12x8/sin_12x8.xci
# IP: The module: 'sin_12x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lukas/01_Studium/02_DigiSys_CAE/Projektaufgabe/signal_generator_vivado/signal_generator_vivado.srcs/sources_1/ip/sin_12x8/sin_12x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sin_12x8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lukas/01_Studium/02_DigiSys_CAE/Projektaufgabe/signal_generator_vivado/signal_generator_vivado.srcs/sources_1/ip/sin_12x8/sin_12x8.xci
# IP: The module: 'sin_12x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lukas/01_Studium/02_DigiSys_CAE/Projektaufgabe/signal_generator_vivado/signal_generator_vivado.srcs/sources_1/ip/sin_12x8/sin_12x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sin_12x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
